//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("NCastor")]
[assembly: AssemblyDescription("NCastor Console Application")]
[assembly: AssemblyCompany("Jupaol Systems")]
[assembly: AssemblyProduct("NCastor")]
[assembly: AssemblyCopyright("Copyright (c) 2012, Jupaol Systems")]
[assembly: AssemblyTrademark("Jupaol Systems - NCastor, All Rights Reserved")]


